Feature/cypress
indiana-university/rivet-switch pull request #10
Opened 2019-02-26 16:12 UTC by illusivesunrae

Installed Cypress and created tests for the Rivet switch add-on.

2019-02-26 17:51 UTC, levimcg requested changes
Nice, this looks great. One small change. We're moving toward all indentation being two spaces. Looks like everything in `switch_spec.js` is four.

You might also look at what it would take to add a couple of assertions that can test the switch custom events that get emitted (`switchOn`, and `switchOff`). Not a directive for this PR, but it could be a nice way to get a bit more familiar with the Cypress API.

2019-02-27 15:01 UTC, levimcg requested changes
Good job on the custom event tests. 👍 

Some minor formatting stuff here. Also, while your at it would mind updating the `.gitignore` to match the collapsible? Thanks!

2019-02-27 15:01 UTC, levimcg commented on cypress/integration/switch_spec.js
> +      });
In these blocks and below, let's add some empty lines between statements just to make it more readable. For example, between the `win.addEventListener` and `const toggleSwitch = ...` statements.

Generally speaking, we should add an empty line between each, non-chainable (like Promise `.then()`, or method calls on an Object). I realize there are places above where I broke this rule 😬

2019-02-27 15:21 UTC, levimcg approved these changes
💯

2019-02-27 15:24 UTC, closed without merging

2019-02-27 15:37 UTC, illusivesunrae commented
Addressed issue #9.